### ISSUE TITLE
Change camera source

### ISSUE THREAD

**Issue by FilippoVannella** [szaza/android-yolo-v2#10]
Hello,

I am developing a drone object detection application with a DJI drone. I have my trained model and it is working by changing the assets as you explained in the guide. 

I am now tying to change the camera source with the DJI camera whose minimum resolution is 1280x720. I am able to run the detector on the drone video source but the bitmap on which the detection run is distorted and the bounding boxes displayed are meaningless.

 I would like to understand better how the detection process work in this application and how you manage to get the 416x416 bitmap from the android camera correctly in such a way to modify in the same way the stream video coming from the drone camera of this application. Thanks a lot for your time

BR

**Comment by szaza** [comment]
Hi,
First of all, I am very glad that you reused this little example project for developing your drone object detection application. The process to capture the video stream and to transform into the required sizes is a little bit complicated, but let me try to explain it shortly.

The main component for the video capturing is the [CameraConnectionFragment](https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/view/CameraConnectionFragment.java), which uses the camera2 API to get the video stream. It uses the ImageFormat.YUV_420_888 format, which has several advantages over the standard RGB representation. For more information about the YUV representation please see this article: [https://en.wikipedia.org/wiki/YUV]( https://en.wikipedia.org/wiki/YUV).

The second most important class for the video stream processing is the [ClassifierActivity](https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/view/ClassifierActivity.java) which uses the CameraConnectionFragment by extending the [TextToSpeechActivity](https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/view/TextToSpeechActivity.java), which extends the [CameraActivity](https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/view/CameraActivity.java).
Inside the onPreviewSizeChosen() method a bitmap is created, named _croppedBitmap_, which it is used for storing temporarly each frames. This method also defines the transformations to resize and rotate the input image:  _frameToCropTransform_.

The [ClassifierActivity](https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/view/ClassifierActivity.java).onImageAvailable method is called when an input image arrives through the camera2 API and it executes the fillCroppedBitmap() method, which is the most important method.
It converts the YUV input bytes to bitmap format by using the ImageUtils.convertYUVToARGB() method, then executes the transformation which is defined in the _frameToCropTransformation_ variable. Finally, the result is copied to the _croppedBitmap_ which is forwarded to the YOLOv2 classifier. The transformations mentioned above are executed for each frames.

I also had problems with the quality of the images and with the accuracy of the tiny yolov2. Unfortunately, I could only resolve it by creating a client-server architecture. This way I could process larger images, and I could use more accurate models than the tiny yolov2. If you are interested in the solution please see this repository: https://github.com/szaza/set-detector. This way you can stream a video for the server, which processes your request and sends back the results.

I hope that these information help you and I wish all the best for your further work!

Best regards,
   Zoltan
