### ISSUE TITLE
not same checking your image

### ISSUE THREAD

**Issue by pdh930105** [szaza/android-yolo-v2#11]
Hello Guy. I'm university student.
As a matter of fact, I'm testing your android-yolo-v2 to galaxy s8+ not change code.
but not Recognized your example.

for example, your image [https://github.com/szaza/android-yolo-v2/blob/master/sample/android-yolo-v2.1.png](url) that my camera only recognized dogs, not bicycle and car

By any chance, Do I have to insert .pb file?

**Comment by szaza** [comment]
Hi,
Did you use my pre-trained .pb file?

**Comment by pdh930105** [comment]
oh sorry. I missed test OTL.  your .pb and android-yolo-v2 is good recognized. So I want better perception of accuracy. so I will make good .pb file. and your android-yolo-v2 changing .pb and labels.txt, asset folder, config.java ... etc Is this possible with this projects?

**Comment by szaza** [comment]
Yes, it is possible. With a better trained model you can achieve a better accuracy. You only have to replace the .pb file and the labels.

**Comment by pdh930105** [comment]
Thanks, You so good programmer.  then I'll ask you again when I have a new question.
