### ISSUE TITLE
Accuracy .

### ISSUE THREAD

**Issue by SteveIb** [szaza/android-yolo-v2#12]
Hi, 
Thanks for your work.
I just gave it a run .. to have a feeling how it is working
the network is not really giving the right object .. it gives a prediction of tv monitor while im showing a bottle.
I tried it with and Android mobile  without GPU and another Android with GPU. they needed almost the same time. I just noticed that the GPU Android get heated quickly. maybe capture image and send it for prediction would be good idea instead of keep sending frames.

one last thing, any recommendations for the network size? the pb file? I have around 1800 images and many objects inside them.

**Comment by aaronhan92** [comment]
Hi Szaza, 

I'm not able to run your YoloV2 app after export (finished training with my own dataset) both of my .pb and label.txt file to android/asset/folder to replace tiny-yolov2.pb and label.txt. 

Please kindly advise.
