### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by chetan1836** [szaza/android-yolo-v2#19]
When I run the app it is just showing a black screen and nothing else.

**Comment by szaza** [comment]
Hi,
What is the error message in the logcat?

**Comment by chetan1836** [comment]
I'm not getting any error message in the logcat. But when I first ran the code there was an error about NDK toolchain, so I changed the Gradle version to 4.6 and Android plugin version to 3.2.1 then it ran fine but I'm getting a black screen.
