### ISSUE TITLE
Do you have no intention of making android-yolo-v3?

### ISSUE THREAD

**Issue by JaeBeom-Bae** [szaza/android-yolo-v2#20]
i think yolov3 performance is much better than yolov2.
do you have no intention of making android-yolo-v3?

**Comment by szaza** [comment]
Hi,
Thank you for interesting about the status of this project, I'm very glad when I get similar comments like your. I plan to develop a version with yolo-v3, however currently I'm working hardly on another project, so I do not have time to do it. I really hope that I can continue developing in the near future.
Best regards,
   Zoltan

**Comment by JaeBeom-Bae** [comment]
Thank you for thinking about developing it.
I'll wait until the yolov3 is developed.
Best regards,
JaeBeom-Bae
