### ISSUE TITLE
How  to train my own dataset?

### ISSUE THREAD

**Issue by xuzongping** [szaza/android-yolo-v2#4]
Hello, I need to change my own dataset. How do I need to train it?

**Comment by szaza** [comment]
Hi, I've written a step-by-step guide to retrain YOLO. Here you can find the description: https://sites.google.com/view/tensorflow-example-java-api/complete-guide-to-train-yolo. It can be retrained either by using DarkFlow or using DarkNet. I also created some Google Colab interactive tutorial for the training process, so you can try it out on a virtual machine.
