### ISSUE TITLE
Conversion of .weights file to .pb file by darkflow

### ISSUE THREAD

**Issue by keides2** [szaza/android-yolo-v2#6]
Hi,
I converted the .weights file trained using darknet into .pb file using darkflow and installed APK on Android cellphone, but fails to launch the application.
Is this conversion failed?

procedure:
1. $ cd ~/darknet
2. $ ./darknet detector train cfg/voc.data cfg/yolov2-tiny-voc.cfg bin/darknet19_448.conv.23
3. $ cd ~/darkflow
4. $ ./flow --module cfg/yolov2-tiny-voc.cfg --load bin/yolov2-tiny- voc-100.weights --savepb

result:
/home/keides2/darkflow/darkflow/dark/darknet.py: 54: UserWarning: ./cfg/yolov2-tiny-voc_100.cfg not found, use cfg / yolov2-tiny-voc.cfg instead
  cfg_path, FLAGS.model))
Parsing cfg / yolov 2 - tiny - voc.cfg
Loading bin / yolov 2 - tiny - voc - 100.weights ...
Successfully identified 63082056 bytes
Finished in 0.0044057369232177734s

Building net ...
Source | Train? | Layer description | Output size
------- + -------- + --------------------------------- - + ---------------
       | | input | (?, 416, 416, 3)
 Load | Yep! | Conv 3x 3 p 1 _ 1 + b norm leaky | (?, 416, 416, 16)
 Load | Yep! | Maxp 2 x 2 p 0 _ 2 | (?, 208, 208, 16)
 Load | Yep! | Conv 3x 3 p 1 _ 1 + b norm leaky | (?, 208, 208, 32)
 Load | Yep! | Maxp 2 x 2 p 0 _ 2 | (?, 104, 104, 32)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 104, 104, 64)
 Load | Yep! | Maxp 2 x 2 p 0 _ 2 | (?, 52, 52, 64)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 52, 52, 128)
 Load | Yep! | Maxp 2 x 2 p 0 _ 2 | (?, 26, 26, 128)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 26, 26, 256)
 Load | Yep! | Maxp 2 x 2 p 0 _ 2 | (?, 13, 13, 256)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 13, 13, 512)
 Load | Yep! | Maxp 2 x 2 p 0 _ 1 | (?, 13, 13, 512)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 13, 13, 1024)
 Load | Yep! | Conv 3x3p1_1 + bnorm leaky | (?, 13, 13, 1024)
 Load | Yep! | Conv 1 x 1 p 0 _ 1 linear | (?, 13, 13, 30)
------- + -------- + --------------------------------- - + ---------------
Running entirely on CPU
2018-07-02 13: 26: 24.956143: I tensorflow / core / platform / cpu_feature_guard.cc: 140] Your CPU support instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-02 13: 26: 25.064272: I tensorflow / stream_executor / cuda / cuda_gpu_executor.cc: 898] successful NUMA node read from SysFS had negative value (-1), but there must always be at least one NUMA node, so returning NUMA node zero
2018-07-02 13: 26: 25.065139: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 1356] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate (GHz): 1.759
pciBusID: 0000: 01: 00.0
totalMemory: 7.93GiB freeMemory: 7.22GiB
2018-07-02 13: 26: 25.065176: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 1435] Adding visible gpu devices: 0
2018-07-02 13: 26: 26.025166: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-02 13: 26: 26.025209: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 929] 0
2018-07-02 13: 26: 26.025235: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 942] 0: N
Finished in 2.7535111904144287s

Rebuild a constant version ...
2018-07-02 13: 26: 26.655822: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 1435] Adding visible gpu devices: 0
2018-07-02 13: 26: 26.655875: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-02 13: 26: 26.655886: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 929] 0
2018-07-02 13: 26: 26.655896: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 942] 0: N
2018-07-02 13: 26: 26.663997: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 1435] Adding visible gpu devices: 0
2018-07-02 13: 26: 26.664021: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-02 13: 26: 26.664029: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 929] 0
2018-07-02 13: 26: 26.664034: I tensorflow / core / common_runtime / gpu / gpu_device.cc: 942] 0: N
Created TensorFlow device (/ job: localhost / replica: 0 / task: 0 / device: GPU: 0 with 6972] Created TensorFlow device MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000: 01: 00.0, compute capability: 6.1)
Done
(tensorflow) [keides2@bslpc ~/darkflow] $

**Comment by szaza** [comment]
Hi,
Could you please copy the exception which you get on the Android device?
You also can try out the retrained model with this demo application: https://github.com/szaza/tensorflow-java-examples-spring.

**Comment by keides2** [comment]
@szaza Thank you for your response.
Unfortunately, instead of throwing an exception, the application will be closed as soon as it is indicated that "YOLOv2 has stopped" at startup. Restarting the application is the same.

**Comment by szaza** [comment]
Hi,
Sorry for replying so late, I was very occupied in the last days.
Yes, theoretically it should be enough to copy the protobuff and labels file into the assets folder then rename them. 
Are you sure that you do not get any exception in the terminal window when you run the application in debug mode with Android Studio?
Can you share the newly trained weights with me in private in order to check it (my mail address is: szabozoltanbors[at]gmail[dot]com)?
Have you tried to use the newly trained weights with the darkflow or darknet? Probably, it is a good idea to check its correctness before converting it into the protobuff file. Also a good idea to check it with darkflow after the conversion.

**Comment by keides2** [comment]
@szaza Sharing the weights file is fine.
Because the weights file used the data set of winnie-the-pooh and tiger listed in the Java API Example TensorFlow.

The weights file(zipped) is 56MB, so can I send it to you by e-mail?

I am able to detect the object from the image using the trained weights file.
![predictions](https://user-images.githubusercontent.com/18452832/42298361-753a2116-8040-11e8-8bbd-165dd8013dec.png)

`./darknet detector test cfg/voc.data cfg/yolov2-tiny-voc.cfg backup/yolov2-tiny-voc_500.weights data/pooh-tiger/37.jpg`

> data/pooh-tiger/37.jpg: Predicted in 0.004631 seconds.
> winnie-the-pooh: 46%
> tiger: 87%
> tiger: 63%
> winnie-the-pooh: 44%
> Not compiled with OpenCV, saving to predictions.png instead


I do not know how to detect an object from an image using the converted pb file.
I tried the command below, but in both cases an AssertionError occurred.

```
./flow --imgdir sample_img/ --model cfg/yolov2-tiny-voc.cfg --load built_graph/yolov2-tiny-voc.weights
./flow --imgdir sample_img/ --model cfg/yolov2-tiny-voc.cfg --load built_graph/yolov2-tiny-voc.pb

```
`AssertionError: expect 63102556 bytes, found 63471556
`
I modified self.offset = 16 in loader.py to self.offset = 20, but it does not improve.

By the way, the following exceptions were occurring.
Failed to load model from 'file:///android_asset/tiny-yolo-voc-graph.pb'
###

> 07/05 09:55:11: Launching android-yolo-v2-master
> $ adb shell am start -n "org.tensorflow.yolo/org.tensorflow.yolo.view.ClassifierActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
> Connecting to org.tensorflow.yolo
> Waiting for application to start debug server
> Waiting for application to come online: org.tensorflow.yolo | org.tensorflow.yolo.test
> Connecting to org.tensorflow.yolo
> Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
> D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
> W/ActivityThread: Application org.tensorflow.yolo is waiting for the debugger on port 8100...
> I/System.out: Sending WAIT chunk
> I/art: Debugger is active
> Connected to the target VM, address: 'localhost:8601', transport: 'socket'
> I/art: Starting a blocking GC Instrumentation
> I/System.out: Debugger has connected
>               waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: waiting for debugger to settle...
> I/System.out: debugger has settled (1481)
> I/InstantRun: starting instant run server: is main process
> D/ViewRootImpl@230c34d[ClassifierActivity]: ThreadedRenderer.create() translucent=false
> D/InputTransport: Input channel constructed: fd=75
> D/ViewRootImpl@230c34d[ClassifierActivity]: setView = DecorView@128313[ClassifierActivity] touchMode=true
> D/ViewRootImpl@230c34d[ClassifierActivity]: dispatchAttachedToWindow
> D/ViewRootImpl@230c34d[ClassifierActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 516329678336} surfaceGenerationChanged=true
> D/ViewRootImpl@230c34d[ClassifierActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 516329678336} hwInitialized=true
> D/ViewRootImpl@230c34d[ClassifierActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
> D/ViewRootImpl@230c34d[ClassifierActivity]: MSG_WINDOW_FOCUS_CHANGED 1
> D/ViewRootImpl@230c34d[ClassifierActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 516329678336}
> D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
> I/OpenGLRenderer: Initialized EGL, version 1.4
> D/OpenGLRenderer: Swap behavior 1
> D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
> V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@6534749 nm : org.tensorflow.yolo ic=null
> I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
> D/InputTransport: Input channel constructed: fd=83
> I/Choreographer: Skipped 4146 frames!  The application may be doing too much work on its main thread.
> I/CameraManagerGlobal: Connecting to camera service
> I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
> E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
> I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
> I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
> D/AndroidRuntime: Shutting down VM
> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: org.tensorflow.yolo, PID: 9387
>                   java.lang.RuntimeException: Failed to load model from 'file:///android_asset/tiny-yolo-voc-graph.pb'
>                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:100)
>                       at org.tensorflow.yolo.TensorFlowImageRecognizer.create(TensorFlowImageRecognizer.java:42)
>                       at org.tensorflow.yolo.view.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:59)
>                       at org.tensorflow.yolo.view.CameraActivity.lambda$setFragment$0$CameraActivity(CameraActivity.java:119)
>                       at org.tensorflow.yolo.view.CameraActivity$$Lambda$0.onPreviewSizeChosen(Unknown Source)
>                       at org.tensorflow.yolo.view.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:291)
>                       at org.tensorflow.yolo.view.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:298)
>                       at org.tensorflow.yolo.view.CameraConnectionFragment.access$000(CameraConnectionFragment.java:52)
>                       at org.tensorflow.yolo.view.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:163)
>                       at android.view.TextureView.getHardwareLayer(TextureView.java:389)
>                       at android.view.TextureView.draw(TextureView.java:338)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17296)
>                       at android.view.View.draw(View.java:18080)
>                       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
>                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17291)
>                       at android.view.View.draw(View.java:18080)
>                       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
>                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
>                       at android.view.View.draw(View.java:18321)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17296)
>                       at android.view.View.draw(View.java:18080)
>                       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
>                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17291)
>                       at android.view.View.draw(View.java:18080)
>                       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
>                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17291)
>                       at android.view.View.draw(View.java:18080)
>                       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
>                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
>                       at android.view.View.draw(View.java:18321)
>                       at com.android.internal.policy.DecorView.draw(DecorView.java:919)
>                       at android.view.View.updateDisplayListIfDirty(View.java:17296)
>                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
>                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
>                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
>                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3128)
>                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2924)
>                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2516)
>                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
>                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
>                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
>                       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
>                       at android.view.Choreographer.doFrame(Choreographer.java:638)
>                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
>                       at android.os.Handler.handleCallback(Handler.java:751)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                       at android.os.Looper.loop(Looper.java:154)
>                       at android.app.ActivityThread.main(ActivityThread.java:6682)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
> E/AndroidRuntime: Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: 0-convolutional = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Pad, 0-convolutional/filter). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
>                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
>                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
>                       	... 53 more

###

First, stop with Object.java String toString () and stW = Cannot find local variable 'stW'.
		
Best Regars,

keides2

**Comment by szaza** [comment]
Thanks for the details and the weight files, I will check it as soon as possible.

**Comment by szaza** [comment]
Hi,
I've checked your .pb file which you sent me in mail and surprisingly it worked for me. I've checked it on a Huawei P9 Lite and also on my laptop by using this implementation:  https://github.com/szaza/tensorflow-java-examples-spring. Here you can see the result:
![tiger-and-winnie](https://user-images.githubusercontent.com/4096582/42423017-5992d864-82fb-11e8-8c55-b3572757f80b.png)
Ok, it wasn't so accurate, probably it can be trained further.

I am wondering on this assertion error: AssertionError: expect 63102556 bytes, found 63471556. Have you changed the number of classes in the configuration file?

**Comment by keides2** [comment]
Thank you for checking the pb file. I was looking forward to hearing from you.

Classes and filters are changing. Could you please check the cfg file that I am sharing with you on google drive?

This device is Samsung. I will try another device.

If the number of learning times is small, will fatal error occur when reading .pb files?

Thank you again,

送信者: YOGA Tablet 2-830L

2018/07/09 4:11 Zoltán Szabó <notifications@github.com>:

**Comment by keides2** [comment]
Additional Information:
I also ran using locally installed tensorflow-java-examples-spring.
I replaced yolo-voc.pb in graph/YOLO and edited yolo-voc-labelas.txt.
The result is that accuracy is not good, but no error was issued.

Is it a device problem?
I can not think so because the original .pb file works without problems.

**Comment by szaza** [comment]
Hi,
I've found only the  .weights file, .pb file and DarknetConf files on the google drive?
Which link contains the .cfg file?

"The result is that accuracy is not good, but no error was issued." - it should be trained further, so the accuracy will increase.

I don't think so that it is a device problem, however both protobuff files ran on my phone without any problems.

**Comment by keides2** [comment]
I'm sorry I could not share the cfg file.
Please check the link below.
[cfg](https://drive.google.com/file/d/1lGjdB81pPxCvZ5dJafTAKON2MDf23lYF/view?usp=sharing
)
In addition, this phenomenon appears in Samsung SM - G 920 F (Android 7.0, API 24) and Xperia Z 5 (Android 7.0)

**Comment by keides2** [comment]
I noticed that this problem is the same as Isuue # 5.
Since the version of tensorflow-gpu is 1.8.0, should I modify the dependencies of build.gradle as follows?

build.gradle
dependencies {
compile 'org.tensorflow: tensorflow-android: 1.8.0'
}

The current dependencies are as below.

build.gradle
dependencies {
compile 'org.tensorflow: tensorflow-android: 1.2.0-preview'
}

Thank you in advance.

**Comment by szaza** [comment]
I'm glad that you finally managed to solve the problem and you did not give up to find the solution.
Thank you for your feedback, it is very useful.

**Comment by keides2** [comment]
It now works by modifying it as follows.

```
dependencies {
compile 'org.tensorflow: tensorflow-android:1.6.0'
}
```

Do not put a space between: and 1.
Tensorflow 1.8 seems to be still unstable.
